jwt.secret=0e3c35360082d3533281b7505c30bac84979826ecfbe8e766c9f7c324d55d80e
jwt.expiration=86400
spring.datasource.url=jdbc:sqlite:agriplatform.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=root
spring.datasource.password=7b3010841df7a01cdd4d6ba9ee3060a12e018141e2e2c7c2efd28b098be87873
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
server.port=5001